'use strict';

const NodeType = {
  PROGRAM: 'Program',
  KOTLIN_RAW: 'KotlinRaw',
  UI_LIST: 'UIList',
  UI_DONE: 'UIDone',
  UI_TOPBAR: 'UITopBar',
  SNACKBAR: 'Snackbar',
  BOTTOM_SHEET: 'BottomSheet',
  TAB_LAYOUT: 'TabLayout',
  OPEN_URL: 'OpenUrl',
  SHARE_TEXT: 'ShareText',
  DIAL: 'Dial',
  CLIP_COPY: 'ClipCopy',
  SEND_NOTIFICATION: 'SendNotification',
  HTTP_GET: 'HttpGet',
  REMOVE_FROM: 'RemoveFrom',
  KOTLIN_IMPORT: 'KotlinImport',
  GRADLE_DEP: 'GradleDep',
  ANDROID_PERMISSION: 'AndroidPermission',
  STYLE_DECL: 'StyleDecl',
  STYLE_SET: 'StyleSet',
  STATE_DECL: 'StateDecl',
  NAVIGATE: 'Navigate',
  TOAST: 'Toast',
  ALERT: 'Alert',
  BACK: 'Back',

  // التعابير
  NUMBER: 'NumberLiteral',
  STRING: 'StringLiteral',
  BOOLEAN: 'BooleanLiteral',
  NULL: 'NullLiteral',
  IDENTIFIER: 'Identifier',
  BINARY: 'BinaryExpr',
  UNARY: 'UnaryExpr',
  CALL: 'CallExpr',
  MEMBER: 'MemberExpr',
  INDEX: 'IndexExpr',
  PIPE: 'PipeExpr',
  ARRAY: 'ArrayLiteral',
  OBJECT: 'ObjectLiteral',
  ASSIGN_EXPR: 'AssignExpr',
  IF_EXPR: 'IfExpr',

  // الجمل
  PRINT: 'PrintStmt',
  EXPR_STMT: 'ExprStmt',
  LET: 'LetStmt',
  CONST: 'ConstStmt',
  ASSIGN: 'AssignStmt',
  IF: 'IfStmt',
  WHILE: 'WhileStmt',
  FOR: 'ForStmt',
  FUNCTION: 'FunctionDecl',
  RETURN: 'ReturnStmt',
  BREAK: 'BreakStmt',
  CONTINUE: 'ContinueStmt',
  IMPORT: 'ImportStmt',
  BLOCK: 'Block',

  // واجهات أندرويد
  SCREEN: 'Screen',
  UI_HEADING: 'UIHeading',
  UI_TEXT: 'UIText',
  UI_BUTTON: 'UIButton',
  UI_CARD: 'UICard',
  UI_TEXTFIELD: 'UITextField',
  UI_IMAGE: 'UIImage',
  UI_CHECKBOX: 'UICheckBox',
  UI_SWITCH: 'UISwitch',
  UI_PROGRESS: 'UIProgress',
  UI_ROW: 'UIRow',
  UI_SPACER: 'UISpacer',
  UI_DIVIDER: 'UIDivider',
};

const AST = {
  Program: (body) => ({ type: NodeType.PROGRAM, body }),
  UICard: (title, children, props = {}) => ({ type: NodeType.UI_CARD, title, children, props }),
  UITextField: (hint) => ({ type: NodeType.UI_TEXTFIELD, hint }),
  UIImage: (name) => ({ type: NodeType.UI_IMAGE, name }),
  UICheckBox: (text) => ({ type: NodeType.UI_CHECKBOX, text }),
  UISwitch: (text) => ({ type: NodeType.UI_SWITCH, text }),
  UIProgress: (value) => ({ type: NodeType.UI_PROGRESS, value }),
  UIRow: (children) => ({ type: NodeType.UI_ROW, children }),
  UISpacer: (size) => ({ type: NodeType.UI_SPACER, size }),
  UIDivider: () => ({ type: NodeType.UI_DIVIDER }),
  KotlinRaw: (code) => ({ type: NodeType.KOTLIN_RAW, code }),
  UIList: (source, template) => ({ type: NodeType.UI_LIST, source, template }),
  UIDone: () => ({ type: NodeType.UI_DONE }),
  UITopBar: (props) => ({ type: NodeType.UI_TOPBAR, props }),
  Snackbar: (text) => ({ type: NodeType.SNACKBAR, text }),
  BottomSheet: (title, items) => ({ type: NodeType.BOTTOM_SHEET, title, items }),
  TabLayout: (tabs) => ({ type: NodeType.TAB_LAYOUT, tabs }),
  OpenUrl: (url) => ({ type: NodeType.OPEN_URL, url }),
  ShareText: (text) => ({ type: NodeType.SHARE_TEXT, text }),
  Dial: (phone) => ({ type: NodeType.DIAL, phone }),
  ClipCopy: (text) => ({ type: NodeType.CLIP_COPY, text }),
  SendNotification: (title, body) => ({ type: NodeType.SEND_NOTIFICATION, title, body }),
  HttpGet: (url) => ({ type: NodeType.HTTP_GET, url }),
  RemoveFrom: (list, item) => ({ type: NodeType.REMOVE_FROM, list, item }),
  KotlinImport: (path) => ({ type: NodeType.KOTLIN_IMPORT, path }),
  GradleDep: (spec) => ({ type: NodeType.GRADLE_DEP, spec }),
  AndroidPermission: (name) => ({ type: NodeType.ANDROID_PERMISSION, name }),
  StyleDecl: (name, value) => ({ type: NodeType.STYLE_DECL, name, value }),
  StyleSet: (name, value) => ({ type: NodeType.STYLE_SET, name, value }),
  StateDecl: (name, init, persistent = false) => ({ type: NodeType.STATE_DECL, name, init, persistent }),
  Navigate: (target) => ({ type: NodeType.NAVIGATE, target }),
  Toast: (text) => ({ type: NodeType.TOAST, text }),
  Alert: (title, message, handler) => ({ type: NodeType.ALERT, title, message, handler }),
  Back: () => ({ type: NodeType.BACK }),
  UITextField: (hint, binding, props = {}) => ({ type: NodeType.UI_TEXTFIELD, hint, binding, props }),

  Number: (value) => ({ type: NodeType.NUMBER, value }),
  String: (value) => ({ type: NodeType.STRING, value }),
  Boolean: (value) => ({ type: NodeType.BOOLEAN, value }),
  Null: () => ({ type: NodeType.NULL }),
  Identifier: (name) => ({ type: NodeType.IDENTIFIER, name }),

  Binary: (op, left, right) => ({ type: NodeType.BINARY, op, left, right }),
  Unary: (op, arg, prefix = true) => ({ type: NodeType.UNARY, op, arg, prefix }),
  Call: (callee, args) => ({ type: NodeType.CALL, callee, args }),
  Member: (obj, prop) => ({ type: NodeType.MEMBER, object: obj, property: prop }),
  Index: (obj, index) => ({ type: NodeType.INDEX, object: obj, index }),
  Pipe: (left, right) => ({ type: NodeType.PIPE, left, right }),
  Array: (elements) => ({ type: NodeType.ARRAY, elements }),
  Object: (properties) => ({ type: NodeType.OBJECT, properties }),
  AssignExpr: (target, value) => ({ type: NodeType.ASSIGN_EXPR, target, value }),
  IfExpr: (test, consequent, alternate) => ({ type: NodeType.IF_EXPR, test, consequent, alternate }),

  Print: (arg) => ({ type: NodeType.PRINT, arg }),
  ExprStmt: (expr) => ({ type: NodeType.EXPR_STMT, expr }),
  Let: (name, init, mutable) => ({ type: NodeType.LET, name, init, mutable }),
  Const: (name, init) => ({ type: NodeType.CONST, name, init }),
  Assign: (target, value) => ({ type: NodeType.ASSIGN, target, value }),
  If: (test, consequent, alternate) => ({ type: NodeType.IF, test, consequent, alternate }),
  While: (test, body) => ({ type: NodeType.WHILE, test, body }),
  For: (variable, iterable, body) => ({ type: NodeType.FOR, variable, iterable, body }),
  Function: (name, params, body) => ({ type: NodeType.FUNCTION, name, params, body }),
  Return: (arg) => ({ type: NodeType.RETURN, arg }),
  Break: () => ({ type: NodeType.BREAK }),
  Continue: () => ({ type: NodeType.CONTINUE }),
  Import: (names, from, alias) => ({ type: NodeType.IMPORT, names, from, alias }),
  Block: (body) => ({ type: NodeType.BLOCK, body }),

  // واجهات
  Screen: (name, children) => ({ type: NodeType.SCREEN, name, children }),
  UIHeading: (text, colorRef = null, props = {}) => ({ type: NodeType.UI_HEADING, text, colorRef, props }),
  UIText: (expr, colorRef = null, props = {}) => ({ type: NodeType.UI_TEXT, expr, colorRef, props }),
  UIButton: (text, handler, colorRef = null, props = {}) => ({ type: NodeType.UI_BUTTON, text, handler, colorRef, props }),
  UICard: (title, children) => ({ type: NodeType.UI_CARD, title, children }),
};

module.exports = { NodeType, AST };
