'use strict';

const TokenType = {
  NUMBER: 'NUMBER',
  STRING: 'STRING',
  IDENT: 'IDENT',
  KEYWORD: 'KEYWORD',

  PLUS: 'PLUS', MINUS: 'MINUS', STAR: 'STAR', SLASH: 'SLASH',
  PERCENT: 'PERCENT', ASSIGN: 'ASSIGN',
  EQ: 'EQ', NEQ: 'NEQ', LT: 'LT', GT: 'GT', LTE: 'LTE', GTE: 'GTE',
  AND: 'AND', OR: 'OR', NOT: 'NOT',
  PIPE: 'PIPE', ARROW: 'ARROW', FAT_ARROW: 'FAT_ARROW',
  DOT: 'DOT', COMMA: 'COMMA', COLON: 'COLON', SEMICOLON: 'SEMICOLON',

  LPAREN: 'LPAREN', RPAREN: 'RPAREN',
  LBRACE: 'LBRACE', RBRACE: 'RBRACE',
  LBRACKET: 'LBRACKET', RBRACKET: 'RBRACKET',

  NEWLINE: 'NEWLINE',
  EOF: 'EOF',
};

module.exports = { TokenType };
